on:
  push:
    branches:
      - master
jobs:
  updateGraphs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Generate csv
        run: python data/get_csv.py

      - name: Update csv
        run: |
          git config --global user.name 'dvaldes8128'
          git config --global user.email 'dvaldes8128@users.noreply.github.com'
          git commit -am "Update csv"
          git push
