on:
  push:
    branches:
      - master
jobs:
  updateCsv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas  

      - name: Generate csv
        run: python data/get_csv.py

      - name: Update csv
        run: |
          git config --global user.name 'dvaldes8128'
          git config --global user.email 'dvaldes8128@users.noreply.github.com'
          git commit -am "Update csv"
          git push
